### ISSUE TITLE
Unable to use kallisto2matrix on linux 

### ISSUE THREAD

**Issue by YUANMENG-1** [yukaiquan/kallisto2matrix#1]
<img width="745" alt="image" src="https://github.com/yukaiquan/kallisto2matrix/assets/63181169/a8631a60-8e13-4369-8da9-898d49310027">
 and here is wrong :
For linux "cargo.exe? build --release --target=x86_64-unknown-linux-musl"
maybe without exe?

But running cargo build --release --target=x86_64-unknown-linux-musl under the  folder kallisto2matrix also meet this problem: error: could not compile `hashbrown` (lib) due to 888 previous errors

**Comment by yukaiquan** [comment]
sorry，Here I used windowse for development, cross-platform compilation, so I added the .exe suffix, in fact on linux compilation just need to "cargo build --release". You can also use the linux executable "https://github.com/yukaiquan/kallisto2matrix/blob/main/kallisto2matrix" which I compiled directly.

**- linux**：https://github.com/yukaiquan/kallisto2matrix/releases/download/v1.0.3/kallisto2matrix
**- Windows**：https://github.com/yukaiquan/kallisto2matrix/releases/download/v1.0.3/kallisto2matrix.exe

**Comment by YUANMENG-1** [comment]
Thanks so much but after Cargo --release finished, the kallisto2matrix file can not be recongnized as tools?
<img width="755" alt="image" src="https://github.com/yukaiquan/kallisto2matrix/assets/63181169/426e44cc-7d41-45cc-8159-4d735fcc62e1">

**Comment by YUANMENG-1** [comment]
Although in release folder, the kallisto2matrix loooks executable, but can not use 
<img width="965" alt="image" src="https://github.com/yukaiquan/kallisto2matrix/assets/63181169/870c7f68-c6ad-499e-9a9c-a641a4fa0325">

**Comment by yukaiquan** [comment]
Apologies for the mistake; I didn't realize the issue comments were closed. To run the program, set the environment variables or use the full path, like this: `./kallisto2matrix -h`.
