### ISSUE TITLE
how to solve the rust bug?

### ISSUE THREAD

**Issue by netwon123** [yukaiquan/kallisto2matrix#2]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:222:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by yukaiquan** [comment]
The sample file you enter must follow our example exactly, check out the following case link: https://github.com/yukaiquan/kallisto2matrix/blob/main/example/samples.txt

**Comment by netwon123** [comment]
> The sample file you enter must follow our example exactly, check out the following case link: https://github.com/yukaiquan/kallisto2matrix/blob/main/example/samples.txt

It's OK! Thank you very muck!
